### PR TITLE
Add sheikh Muhammad Rashad Shereef

### PR DESCRIPTION
**Pull request by ahmedre**

### CODE REVIEW

**Comment by ahmedre** [comment]
jazakumAllah khairan @naushervan for contributing this recitation.

**Comment by naushervan** [comment]
JazākAllāhu khairā brother! 

Perhaps it's going to take some time for the update to reach our phones as it's not available yet. I'll check it again tomorrow, in-shāʾAllāh.

I also wanted to bring to your notice that the reciter's list is not fully alphabetically sorted. Most of the names are sorted, but a couple are not. Dr. Ayman Suwaid and Minshawy Mujawwad are mistakenly at the very end of the list.

**Comment by ahmedre** [comment]
waiyyakum - update hasn't been posted yet akhi, but in sha' Allah hoping to get one out before Ramadan.

re: sorting - it's because non-gapless recitations are left to the bottom of the list to discourage people from using them. we hope to eventually move away from gapped recitations.

**Comment by naushervan** [comment]
JazākAllāhu khairā for informing me about the state of the app, as I was assuming that the app may have been updated already. 

It will be most kind of you if you can inform me after the update has been posted so that I can message the brother that his request has been fulfilled. We also need to close the following issue after the app is updated:
https://github.com/quran/quran.com-api/issues/331 

JazākAllāhu khairā!

**Comment by ahmedre** [comment]
waiyyakum, will try to remember to post here, but if I forget, it'll be in the releases tab in sha' Allah.

regarding the linked quran.com-api issue, that's separate because that work is still needed to expose it on the website to people not using the mobile apps (people using quran.com directly).

**Pull request merged**
