### PR TITLE
Remember the last reading mode

### LINKED ISSUE #530: remember selection to see translations
when a user goes into translations, we should probably default them to translations by default.

### PR DESCRIPTION
**Pull request by ozbek**
This will enable going back to translation mode when jump to last page is selected from the action bar.

Fix #530.

### CODE REVIEW

**Comment by ozbek** [comment]
Please don't merge yet. This has side effect on recent pages.

**Comment by ahmedre** [comment]
what is the side effect on recent pages? it might be my bug if so, because otherwise, this seems right (code wise anyway).

**Comment by ozbek** [comment]
> what is the side effect on recent pages?

Once the mode is changed to translation, all entries go to translation mode (from sura list, bookmarks, etc) except from "Jump to" menu (this always opens in Quran mode). I think, I need more details on the "concept" of #530. Should we open the page in previous mode only from "Last page" menu? Or always?

**Comment by ahmedre** [comment]
i am ok either way (i can see the argument for both).

**Comment by ozbek** [comment]
if so, please go ahead and merge :)

**Comment by ahmedre** [comment]
jazakAllah khairan

**Pull request merged**
