### PR TITLE
Changes the Arabic transliteration for sura names. 

### PR DESCRIPTION
**Pull request by muhsinali**
Endings were inconsistent and changes were made to reflect Darussalam's English transliterations & quran.com titles.

### CODE REVIEW

**Comment by ahmedre** [comment]
jazakAllah khairan!

**Comment by ahmedre** [comment]
@muhsinali one minor thing - some of these match what we have on quran.com, but i don't agree with them - for example, adding an ' before Al-'Isra - i think Al-Isra' is more correct. i found this (http://www.noblequran.com/translation/) which is basically almost what you have changed, but with a few of the apostrophes changed.

do you think those may end up being a little better (if we can make those few changes?) jazakAllah khairan!

**Comment by muhsinali** [comment]
@ahmedre not a problem insha'allah I can make those changes. Do you want all the titles to match http://www.noblequran.com/translation/ ? or specifically al-Isra'? Just let me know and I'll update.

**Comment by ahmedre** [comment]
ideally all of them if it's not too much trouble - i imagine the spellings should mostly match, it's just the extra ' that will likely change. should likely change them on quran.com as well insha'Allah. jazakAllah khairan!

**Comment by muhsinali** [comment]
Not a problem at all insha'allah

**Pull request merged**
