### PR TITLE
#1177 Added new feature of export backup as CSV file

### PR DESCRIPTION
**Pull request by jibraniqbal666**
- Added CSV by just making everything by breaking line.
- Did some method extraction to avoid duplicate code.
- Schema will looks as below.

image

Schema:

Tags
--> List of Tags
Bookmarks
--> List of Bookmarks
RecentPages
--> List of Recent Pages.

### CODE REVIEW

**Comment by ahmedre** [comment]
jazakumAllah khairan Jibran - looks good!

2 questions -
1. if I try to import this as is into Google Drive, it might not work - what if we inline tags and add a type field so we can also inline recents? this way we just have a single table that's importable without needing to look up keys, etc? what do you think? something like:

```
type,sura,ayah,page,timestamp,tags
bookmark,1,,1,1650183444000,tag1|tag2|tag3
bookmark,2,1,2,1650190000,tag2
recent,15,,1650000000000,
```

in the above, I made a few tweaks from what you have -
I intentionally dropped ayahText - not needed, but have an ayah id that may or may not be there depending on whether it's an ayah bookmark or a sura bookmark. I changed ; to |, but not necessary, ; is fine. I also dropped the ids because they're irrelevant to someone exporting the data.

2. why the extra space before every new line?

**Comment by jibraniqbal666** [comment]
> 1. if I try to import this as is into Google Drive, it might not work - what if we inline tags and add a type field so we can also inline recents? this way we just have a single table that's importable without needing to look up keys, etc? what do you think? something like:

1. I agree, we don't need tags as list as well, we can just bookmark and recent, i made this schema, so by just seeing the data class, right we should normalize it as recent and bookmark, i will make the changes.
2. just for the readability as i believe it will trimmed down if you import it in proper spreadsheet viewer, i can do trim before writing. :)

**Comment by jibraniqbal666** [comment]
New schema:
image

**Review by ahmedre — APPROVED** [review]

**Comment by ahmedre** [comment]
jazakAllah khair!

**Comment by ibardawil** [comment]
Assalamu alaikum,
import csv file doesn't work

**Comment by ahmedre** [comment]
this feature is just for export - there's an import/export for json format that you should use if you want to import.

**Pull request merged**
