### PR TITLE
FixAudioSuraName

### PR DESCRIPTION
**Pull request by nyitgroup**
Fix: Audio panel does not show the sura names properly (in Farsi) #849
Add weight 1 to linear layout child spinners to fix width

### CODE REVIEW

**Comment by bateni** [comment]
This seems to fix the problem but is sort of hacky...  why doesn't the spinner show the full name of the suras, although it has sufficient width for it?

Can you reproduce the problem for Arabic locale?  I can't.  Why doesn't it occur there?

**Comment by nyitgroup** [comment]
I was looking for a general and quick solution. 
The spinner might be measuring width wrong for different languages. I will look into it, but I can't promise anything quick. :)

**Comment by ahmedre** [comment]
yeah, this is pretty hacky and changes the desired behavior.

unfortunately, this is a pretty tricky problem. here are some notes:
1. if you look at the layout, you'll see that the text doesn't quite fill its parent (the `Spinner`), even though it should.
2. in `QuranSpinner`, we override `onMeasure` to correctly figure out the width of the dropdown - if you notice, the dropdown width is correct because of this. both `Spinner` and `AppCompatSpinner` calculate the dropdown width (and the spinner's width) based on the largest width of the first 15 elements, whereas `QuranSpinner` calculates the last 15 items, and compares that width to the width found from the first 15 items, and uses the largest of the 2.
3. if we disable all the logic in `QuranSpinner`, the  bug still happens, suggesting it's a bug either in `AppCompatSpinner`, or in one of the framework classes that it extends from (`Spinner` or `AbsSpinner`). my guess is that the bug is in `Spinner` itself.
4. if we ask the child to measure in `QuranSpinner`'s `onMeasure` once we decide on a new width to use, this gets overridden later on by `Spinner`'s `setUpChild` method, which measures the view using the `Spinner`'s own layout parameters as a basis.

the least hacky workaround i could come up with here is to explicitly update the spinner's layout parameters once we've determined the width. this will cause any further `setUpChild` calls to use the spinner's current layout parameters, which have a fixed width, and consequently, it solves the problem. i'll push a patch for this insha'Allah.

as for your question - "why does it work for English and Arabic, but not for Farsi?" i think the reason is that there is some bug in the text measurement logic, specifically when you combine Farsi numbers with Farsi text. here are 2 proofs for this:

1. remove the for loop at `AyahPlaybackFragment`, line 170, which prepends the localized number to the sura name - re-run the app and you'll see that it now works, just like Arabic and English does.
2. undo change 1 if you made it, and then jump into the `QuranUtils.getLocalizedNumber` method, and force `isArabicNames` to true, then re-run. you'll again see that it works just fine.

**Comment by ahmedre** [comment]
i will close this, please re-open if you think it should be re-opened. jazakAllah khairan!

**Pull request closed without merging**
