### PR TITLE
feat: add speedup & down to sound player UI

### PR DESCRIPTION
**Pull request by MahmoudMabrok**
implement the feature at #1529

### CODE REVIEW

**Comment by princeparacha58** [comment]
Assalam mu alikum brother, i need speed up and speed down in quran andriod audio player please add in your software jazakallah

**Comment by MahmoudMabrok** [comment]
@princeparacha58 I think now we have `hadr` recitation, so if still need this feature, we can have a build from this PR, but I think it will not have all data sources in current app version.

closed as  `hadr` recitation added.

**Comment by ahmedre** [comment]
let's keep it open, thinking to merge it but with guidelines on what max speed to set depending on the Qari's rate of recitation, since this remains the top requested feature.

**Comment by MahmoudMabrok** [comment]
if will be merged @ahmedre I would spend today and rest of week on working on it. 

I really want to contribute and help Quran users.

**Comment by ahmedre** [comment]
planning to merge it in sha' Allah - جزاكم الله خيراً for building it and really sorry for being quiet about it all this time (as you know, I was against this idea from earlier on, but after discussions and brother @mohamede1945's idea to keep things beneficial, and it being the top feature request), planning on seeing this through in sha' Allah.

**Comment by MahmoudMabrok** [comment]
No problem my brother, so I think we can make make 1.5(as max to all recitation) until we get a comprehensive solution to be related to Quran recitation type, do you agree @ahmedre ? 

I follow rule said `write, revisit, refactor, enhance`

**Comment by ahmedre** [comment]
Sure, that sounds reasonable. Cc @mohamede1945 fyi

**Comment by MahmoudMabrok** [comment]
@ahmedre  I have pushed the changes. please check

**Review by ahmedre — COMMENTED** [review]
overall looks good, جزاكم الله خيراً

a few minor things:
1. we probably should have some pre-sets instead (ex 0.5x, 0.75x, 1x, 1.25x, 1.5x) instead of a dynamic increase/decrease.
2. if this only works on M+, let's not show the ui components for versions less than M

**Comment by MahmoudMabrok** [comment]
@ahmedre  these pre sets will be in code only or will reflect in UI.

**Comment by ahmedre** [comment]
we'd need to reflect in the UI also. for the audio bar, we can do the same as repeat (if you tap the repeat icon, the number cycles there between the valid repeat amounts). then, we can also expose a similar layout to repeat in the settings bottom sheet.

**Comment by mohamede1945** [comment]
> Sure, that sounds reasonable. Cc @mohamede1945 fyi

Sounds great. Jazak Allah Khyran. And thanks brother @MahmoudMabrok for implementing it.

BTW, Here is the list that the quran.com website shows. I think this PR will be just for [0.5, 0.75, 1, 1.25, 1.5], right?

image

**Comment by ahmedre** [comment]
جزاكم الله خيراً
Did some minor clean up - it's still not ready yet, need to figure out a fix for sura transitions where the speed delta gets lost when one sura ends and another starts to play. Likely need to put the speed inside the `AudioRequest` itself. Will look over the weekend or next week in sha' Allah.

**Comment by MahmoudMabrok** [comment]
I tried to add to `AudioRequest ` but faced a lot of issues. 
I will check ISA.

**Comment by ahmedre** [comment]
@MahmoudMabrok I've fixed some issues (including when we transition suras, the playback speed is now properly maintained). I still see two things before we can merge this:

1. the bigger problem - repeat seek timings are off when repeating at a higher play rate - ex play and press the button to repeat the ayah (and make speed 1.5x) - you'll notice that it reads the ayah and some of the next before going back (at 1x it's fine). note that "seek" itself is fine - i.e. going to the next or previous ayah goes to the correct time stamp.
2. nice to have - expose this in the audio panel settings - I've added the wiring, just needs the ui piece.

I think the first is caused by our audio check being at 1x - we need to run this more (or less) frequently to fix. the second one just needs to be done. just updating you so you know.

**Comment by ahmedre** [comment]
aforementioned changes made al7amdulillah.
جزاكم الله خيراً @MahmoudMabrok

**Comment by MahmoudMabrok** [comment]
Thanks so much for your efforts and merge.

**Pull request merged**
