### PR TITLE
Shorten Russian translation of Sura names

### PR DESCRIPTION
**Pull request by ozbek**
The Sura names are based on Kuliyev's translation from http://islam.by/hq/kul/ (the same translation is provided in Settings->Translations screen).

Fixes https://github.com/quran/quran_android/issues/503.

### CODE REVIEW

**Comment by ozbek** [comment]
@ahmedre, what do you think about this PR? 

I understand that this might not be the fix for root cause of #503, but the current Sura names in Russian are unnecessarily long and have spelling/grammar errors.

**Comment by ahmedre** [comment]
jazakAllah khairan - sorry i forgot to merge this - i think it is a good easy fix for #503. if people complain, we can update the main screen to show the translation as well or something.

**Comment by Valey** [comment]
Some brothers wants full sura names (with russian translation).
For example:
https://play.google.com/store/apps/details?id=com.quran.labs.androidquran&reviewId=Z3A6QU9xcFRPRlA1aE1XbnVxQS1fWl9ybnI1cXExQVdrVExDajdHS3FIWUwyb2ZFQjZFY0lVMVMtbHFWeGo5N3hfbGxzNWtLeTBSWkJDa3lPX0haeWRQLUpv

https://play.google.com/store/apps/details?id=com.quran.labs.androidquran&reviewId=Z3A6QU9xcFRPSFRqNGNmQTlodTJieFlDajBoTWU0Y2VtZ19JV256S0VJQ0pnb2k0NUw1Q0R4a3llMWFpR0p6TzRrTVNvNThRbTRPNWdOUHRBYnNfVXlLdzBB

What a problem with previous full version? And it's more correct Tajwid version (see Al-Muntahab Russian translation from Al-Azhar University).

**Comment by ozbek** [comment]
1. Please see https://github.com/quran/quran_android/issues/503 for the problem with long names, basically long Surah names render dropdown playback controller useless. We should probably put the translations as summaries. 

2. Before updating I searched for Russian translations and the one by Kuliyev seemed more popular. But if you say Al-Muntahab version is more appropriate, we can apply that one insha Allah. 

What do you think?

**Comment by ahmedre** [comment]
i think Al-Muntahab is more appropriate (i am not 100% sure, but i think it's indeed from Al-Azhar). i think we probably want to separate out the short sura names from the translations and only show the translations in certain places, for example.

**Comment by Valey** [comment]
Yes, Russian translation by Kuliyev really popular in web, but most imams recommends Al-Muntahab because it's indeed from Al-Azhar. For the same reason I ask to add other translations, see <a href="https://github.com/quran/quran_android/issues/13#issuecomment-80264615">translations issue</a>. There is almost all translations available at http://beta.quran.com/

Can we show full sura names (with translation) on main menu and reading page, and show short sura names on context menu (for example before playing audio) as fix <a href="https://github.com/quran/quran_android/issues/503">#503</a>?

**Pull request merged**
