### PR TITLE
migrate `model\bookmark` test to Kotlin and update deprecated things

### PR DESCRIPTION
**Pull request by wiryadev**

### CODE REVIEW

**Comment by wiryadev** [comment]
Close this due to failed in Github Actions, couldnt reproduce since all the test passed in my machine. And somehow `BookmarksWidgetSubscriberTest` in this commit even tho i didnt touch it.

image

**Comment by ahmedre** [comment]
Maybe keep it open and when I get to a computer I can check and see if anything stands out in sha' Allah.

**Comment by wiryadev** [comment]
> Maybe keep it open and when I get to a computer I can check and see if anything stands out in sha' Allah.

okay, thank you so much for that

**Comment by ahmedre** [comment]
i took a look at this yesterday and think it's related to migrating to Kotlin, specifically around the hack to work around AndroidSchedulers.mainThread() - see https://stackoverflow.com/questions/43356314/android-rxjava-2-junit-test-getmainlooper-in-android-os-looper-not-mocked-runt

**Comment by wiryadev** [comment]
thanks, and sorry for accidentally reopening this, was going to close this since im about to open new PR that contains no migration like this/

**Pull request closed without merging**
