### PR TITLE
Update UI Strings

### PR DESCRIPTION
**Pull request by benomaire**
Mainly adding missing Arabic strings.

### CODE REVIEW

**Comment by ahmedre** [comment]
جزاكم الله خيراً
let me know when this is ready can merge, barak Allah feekum

**Comment by benomaire** [comment]
Please comment on adding (الوضع العربي) in English. If you don't like it, I will revert it. Otherwise, I think it should be added to other languages.

**Comment by ahmedre** [comment]
sure, in the Arabic one, can we add the English in it as well (get a few people often asking "how do I get out of Arabic mode?" so that would help them also)

**Comment by benomaire** [comment]
But I think that way is not unique! Should we just have English?

**Comment by ahmedre** [comment]
yeah it's not ideal i guess - because depending on the language people have set, the string would be wrong. maybe we leave them as they are for now.

**Comment by benomaire** [comment]
For Arabic,
How about using 
`إلغاء هذا الوضع يؤدي إلى استعمال لغة الجهاز الافتراضية`
instead of
`سيتم تحويل التطبيق إلى اللغة العربية`
?

**Comment by ahmedre** [comment]
I like
سيتم تحويل التطبيق إلى اللغة العربية
more since it's clearer - that selecting this option will cause the app to be in Arabic.

**Comment by benomaire** [comment]
If no other comments, feel free to merge.

**Review by ahmedre — APPROVED** [review]
جزاكم الله خيراً

**Pull request merged**
