### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MahmoudMabrok**
add code analysis
it list each language used in code/project files, count pure lines, blank lines

### CODE REVIEW

**Review by ahmedre — APPROVED** [review]

**Comment by ahmedre** [comment]
didn't realize this was a static image - maybe no point really then? :(

**Comment by MahmoudMabrok** [comment]
what issue of being static image, 
do u want it as dynamic feature
@ahmedre

**Comment by ahmedre** [comment]
we already know the stats of percentage via Github side bar - lines of code is not important to be shared on a page like this imho

**Comment by MahmoudMabrok** [comment]
i thought display LOC may be an indication of how big is our app

**Pull request merged**
