### PR TITLE
Add privacy policy

### LINKED ISSUE #796: privacy policy
long ago, we used to request `READ_PHONE_STATE` permission to stop the audio when a phone call came in. this was removed in September of 2015 [here](https://github.com/quran/quran_android/commit/f516199f5c1560beb2881f5d7f8d84f4ad325f23).

however, i got an email from Google asking us to add a privacy policy or remove the permission. i checked, and all the older apks (that are still live for people with older devices) do use the permission.

should re-build the api 3, api 7, and api 9 apks to fix this. if it is not easily doable, should at least just fix api 9 and remove api 3 and api 7 apks altogether.

or, i could just add a privacy policy.

### PR DESCRIPTION
**Pull request by ozbek**
If merged, this can be linked from Play Store to comply with the Google's request. An alternative solution would be to simply add a wiki page and link to it.

Closes #796.

### CODE REVIEW

**Comment by ahmedre** [comment]
jazakAllah khairan - i'll actually copy / paste this into a privacy.md on android.quran.com and just link it there instead of putting it into the repo - let me keep this PR open until then, at which point i'll close without merging.

**Comment by ahmedre** [comment]
jazakAllah khairan - http://android.quran.com/privacy.html - closing this, used your markdown file and added some minor things about using Fabric. you can also get the md directly from http://android.quran.com/privacy.md

**Comment by ozbek** [comment]
You have missed the link to Github commit at _here_

> That was removed on September 27, 2015 [here](https://github.com/quran/quran_android/commit/f516199f5c1560beb2881f5d7f8d84f4ad325f23) (users running versions released prior to that day may still have it).

**Comment by ahmedre** [comment]
jazakAllah khairan - fixed it and added the link

**Pull request closed without merging**
