### PR TITLE
Improve sharing format of text

### LINKED ISSUE #1769: Suggestion: tafseer sharing text format
السلام عليكم ورحمة الله وبركاته 

I have one suggestion about sharing tafseer text format:

{Ayah or Ayats}
[Surah name:Ayah number]

Tafseer name:
Tafseer text

Ex:
From the app:

ذَٰلِكَ ٱلۡكِتَٰبُ لَا رَيۡبَۛ فِيهِۛ هُدٗى لِّلۡمُتَّقِينَ

(المختصر)
ذلك القرآن العظيم لا شك فيه، لا من جهة تنزيله، ولا من حيث لفظه ومعناه، فهو كلام الله، يهدي المتقين إلى الطريق الموصل إليه.

-سورة البقرة، آية ٢

Suggestion(new format):

{ذَ ٰ⁠لِكَ ٱلۡكِتَـٰبُ لَا رَیۡبَۛ فِیهِۛ هُدࣰى لِّلۡمُتَّقِین}
[سورة البقرة: 2]

:المختصر
ذلك القرآن العظيم لا شك فيه، لا من جهة تنزيله، ولا من حيث لفظه ومعناه، فهو كلام الله، يهدي المتقين إلى الطريق الموصل إليه.

وجزاكم الله خيرا

### PR DESCRIPTION
**Pull request by ahmedre**
Fixes #1769.

### CODE REVIEW

**Comment by ahmedre** [comment]
with one translation:

Arabic:
```
(ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ)
[سورة الفَاتِحَةِ، آية ٣]

الميسر:
﴿الرَّحمَنِ﴾ ذي الرحمة العامة الذي وسعت رحمته جميع الخلق، ﴿الرَّحِيمِ﴾ بالمؤمنين، وهما اسمان من أسماء الله تعالى.
```

English:

```
(ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ)
[Surah Al-Fâtihah, Ayah 2]

Sahih International:
[All] praise is [due] to Allah, Lord of the worlds -
```

with multiple translations:

Arabic:

```
(ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ)
[سورة الفَاتِحَةِ، آية ٣]

الميسر:
﴿الرَّحمَنِ﴾ ذي الرحمة العامة الذي وسعت رحمته جميع الخلق، ﴿الرَّحِيمِ﴾ بالمؤمنين، وهما اسمان من أسماء الله تعالى.

Sahih International:
The Entirely Merciful, the Especially Merciful,
```

English:

```
(ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ)
[Surah Al-Fâtihah, Ayah 2]

Sahih International:
[All] praise is [due] to Allah, Lord of the worlds -

Dr. Mustafa Khattab:
All praise is for Allah—Lord of all worlds,
```

with multiple verses:

Arabic mode
```
(بِسۡمِ ٱللَّهِ ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ ۝  ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَـٰلَمِینَ ۝  ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ)
[سُورَةُ الفَاتِحَةِ 1 - 3]
```

English mode
```
(بِسۡمِ ٱللَّهِ ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ ۝  ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَـٰلَمِینَ ۝  ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ)
[Surah Al-Fâtihah 1 - 3]
```

**Comment by ahmedre** [comment]
cc @nacer80

**Comment by nacer80** [comment]
I suggest:
Single verse:
 Arabic:
{ بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ } 
[سُورَةُ الفَاتِحَةِ:1 ]

English:
{ بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ }
[Surah Al-Fâtihah:1]

Multiple verses:
 Arabic:
{ بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ (1) الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ (2) الرَّحْمَنِ الرَّحِيمِ (3) } 
[سُورَةُ الفَاتِحَةِ: 1-3 ]

English:
{ بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ (1) الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ (2) الرَّحْمَنِ الرَّحِيمِ (3) }
[Surah Al-Fâtihah:1-3]

**Comment by ahmedre** [comment]
جزاكم الله خيراً

**Pull request merged**
