### PR TITLE
Add an easier way to copy an ayah and translation

### PR DESCRIPTION
**Pull request by ahmedre**

### CODE REVIEW

**Comment by ahmedre** [comment]
this is still a work in progress - it's not complete yet.

**Comment by ozbek** [comment]
Hmm... While you are at it, can you consider issue #220 as well: add a context menu with share and bookmark options?

**Comment by ahmedre** [comment]
@ozbek great point masha'Allah - let me think this through some

**Comment by ahmedre** [comment]
abandoning in favor of 2bbfa7c

**Comment by ahmedre** [comment]
btw, this patch makes #220 pretty straight forward to do (add an option for bookmarks in the `share_menu.xml` (and rename it, this is only used by translations), and then make sure that `TranslationPresenter` calls `toggleBookmark` (which is currently `private`)

**Pull request closed without merging**
