### PR TITLE
Implement an improved qari picker

### PR DESCRIPTION
**Pull request by ahmedre**
This changes the spinner of the Qari picker to a bottom sheet that shows
4 categories - qaris that are ready to play (i.e. downloaded on the
device for the current pages), qaris that have downloads (even for other
suras), gapless, and gapped. More categories may be added later.

### CODE REVIEW

**Comment by ahmedre** [comment]
Screenshot_20220725_010742

**Comment by DoozyDoz** [comment]
> Screenshot_20220725_010742

@ahmedre Nice work, I wonder how it will look in dark mode (given the app is predominantly dark)

**Comment by ahmedre** [comment]
JazakAllah khairan - so the nice thing is it's now based on the QuranTheme Compose theme which supports light and dark modes. I'll try it and add a screenshot in sha' Allah.

Haven't merged yet because need to fix the qari list not refreshing upon language change.

**Comment by DoozyDoz** [comment]
Wow, compose is really the future, hope its stable now.

I saw the new branch, shall find time and test it out.

**Comment by ahmedre** [comment]
I'll actually go ahead and merge this and fix the resources issue in another patch, since it'll be a larger change.

**Pull request merged**
