### PR TITLE
Jump to surah and ayah by allowing user to type (issue #799)

### PR DESCRIPTION
**Pull request by fikr4n**
This is the proposal that we've discussed in issue #799.

I want to note that:

1. I assume that all Android devices' numeric soft keyboard use Western Arabic digits (123...) instead of Eastern Arabic digits (١٢٣...), so that ayah number uses Western Arabic digits.
2. When testing by using Arabic, typing "ا-ل-أ-ع" does not make "الأعراف" to show up. It turns out that the sura names in string resource are not normalized, so I've a suggestion to normalize them, probably by using [NFKC](http://unicode.org/reports/tr15/#Norm_Forms). Other issue is that some sura such as الإنفطار is written as `الانفطار`, even comparing by using collator with `PRIMARY` strength will not treat them as equal string.
3. There is a method and a class which can be extracted out of `JumpFragment`, but I am not really sure.
4. I've not renamed the variables and layout IDs yet, to make minimum changes for this prototype.

### CODE REVIEW

**Comment by ahmedre** [comment]
just tried this - this is awesome masha'Allah, jazakAllah khairan!

**Comment by ahmedre** [comment]
oh, and sorry for the delayed reply on this PR - sorry things have been busy - would love it if you would contribute more also insha'Allah.

**Comment by fikr4n** [comment]
وجزاك الله خيرا
It's my pleasure that you allow me to contribute to this project.

I've just remembered that I've not changed the variable names yet, e.g. `ayahSpinner` is still `ayahSpinner` while it should be changed to `ayahText` or `ayahInput` since it's no longer a spinner :D.

**Comment by ozbek** [comment]
@fikr4n, please consider closing #799 :)

**Comment by ahmedre** [comment]
please feel free to open another PR for the variable renames :)

**Pull request merged**
