### PR TITLE
Fix Arabic search

### LINKED ISSUE #427: poor search quality
from an email:
- When search "idhrib" (اضرب) it doesn't show results about "wa
  idhrib" (واضرب), and when search "dharaba" (ضرب), it doesn't show
  results about "madhrib" (مضرب)
- When search "wa" (و) it doesn't show more than 150 results although
  there is "22,226" result for this phrase.

### PR DESCRIPTION
**Pull request by ahmedre**
Al7amdulillah, this patch completely rewrites (and fixes) Arabic search.
It now supports searching with approximate matches for characters that
could have multiple variants in Arabic (i.e. an alif now matches an alif
with a hamza, etc), among other things. It doesn't support tashkeel
search yet, but in practice, this isn't a problem since Arabic search is
only used for searching the Quran text without taskeel.

Fixes #427, #453, #953, and #960.

### CODE REVIEW

**Comment by ahmedre** [comment]
special thanks to @mustafa0x for the replacement characters here.

**Comment by Ahmed9914** [comment]
Fixes #1148

**Comment by ahmedre** [comment]
not yet actually - this patch is only for search itself, the other ticket is for jump

**Comment by Ahmed9914** [comment]
@ahmedre 
You mean another regex matching expression should be added in this block:
https://github.com/quran/quran_android/blob/636396fd9350f3dfe0b8f4e474da3aa06979c3a4/app/src/main/java/com/quran/labs/androidquran/ui/fragment/JumpFragment.java#L102

Is this right?

**Comment by ahmedre** [comment]
yes

**Pull request merged**
