### PR TITLE
Create New Mus'haf Madina fonts

### PR DESCRIPTION
**Pull request by Muslim010101**
https://archive.org/details/qcf-4-hafs-41

### CODE REVIEW

**Comment by ahmedre** [comment]
did you mean to open this as an issue here - https://github.com/quran/quran_android/issues instead?

**Comment by Muslim010101** [comment]
No i just want to share new Qur'an fonts

**Comment by ahmedre** [comment]
ok - but pull request is for adding code to the repository so probably this fits better as an issue with a request to "support new Madinah fonts"

**Comment by Muslim010101** [comment]
> ok - but pull request is for adding code to the repository so probably this fits better as an issue with a request to "support new Madinah fonts"

Sorry but i'm not familiar in github.

**Comment by ahmedre** [comment]
Merged into #1682

**Comment by Muslim010101** [comment]
@ahmedre السلام عليكم ورحمة الله وبركاته 
How i can help you with new Mus'haf Madinah font?

**Comment by ahmedre** [comment]
وعليكم السلام ورحمه الله وبركاته 
Replied in the other issue.
جزاكم الله خيرا

**Pull request closed without merging**
